on:
  rss:
    url: 
      - https://androidstudio.googleblog.com/feeds/posts/default # Android Studio Release Updates
      - http://feeds.feedburner.com/blogspot/hsDu # Android Developers Blog
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps: 
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TITLE: ${{on.rss.outputs.title}}
          LINK: ${{on.rss.outputs.link}}
          CONTENT: ${{on.rss.outputs.content}}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            *${{on.rss.outputs.title}}*
            
            *${{on.rss.outputs.link}}*
