on:
  rss:
    url: 
      - https://medium.com/feed/androiddevelopers # Android Developers on Medium
      - https://blog.jetbrains.com/kotlin/feed/ # Official Kotlin Blog
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps: 
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '{{ on.rss.outputs.title }} \n {{ on.rss.outputs.link }}\n {{ on.rss.outputs.content }}'
