on: 
  youtube:
    channel_id: UCVHFbqXqoYvEWM1Ddxl0QDg # Android Developers on Youtube
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps: 
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TITLE: ${{on.rss.outputs.title}}
          LINK: ${{on.rss.outputs.link}}
          CONTENT: ${{on.rss.outputs.content}}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            *${{on.youtube.outputs.title}}*
            
            ${{on.youtube.outputs.link}}
            
            ${{on.youtube.outputs.description}} 
